window.MUMBAI_METRO_LINES = {
    blue1: {
        code: "M1",
        label: "Blue Line (Line 1)",
        route: "Versova to Ghatkopar",
        stations: [
            "Versova",
            "D N Nagar",
            "Azad Nagar",
            "Andheri",
            "Western Express Highway",
            "Chakala (J. B. Nagar)",
            "Airport Road",
            "Marol Naka",
            "Saki Naka",
            "Asalpha",
            "Jagruti Nagar",
            "Ghatkopar"
        ]
    },
    aqua3: {
        code: "M3",
        label: "Aqua Line (Line 3)",
        route: "Aarey JVLR to Cuffe Parade",
        stations: [
            "Aarey JVLR",
            "SEEPZ",
            "MIDC - Andheri",
            "Marol Naka",
            "Chhatrapati Shivaji Maharaj International Airport - T2",
            "Sahar Road",
            "Chhatrapati Shivaji Maharaj International Airport - T1",
            "Santacruz",
            "Bandra Colony",
            "Bandra Kurla Complex",
            "Dharavi",
            "Shitaladevi Mandir",
            "Dadar",
            "Siddhivinayak",
            "Worli",
            "Acharya Atre Chowk",
            "Science Centre",
            "Mahalaxmi",
            "Jagannath Shankar Sheth",
            "Grant Road",
            "Girgaon",
            "Kalbadevi",
            "Chhatrapati Shivaji Maharaj Terminus",
            "Hutatma Chowk",
            "Churchgate",
            "Vidhan Bhavan",
            "Cuffe Parade"
        ]
    },
    green4: {
        code: "M4",
        label: "Green Line (Line 4)",
        route: "Shivaji Chowk (Mira Road) to Bhakti Park (Wadala)",
        stations: [
            "Shivaji Chowk (Mira Road)",
            "Kashimira",
            "Varsova Char Phata",
            "Gaimukh Reti Bandar",
            "Gaimukh",
            "Gowniwada",
            "Kasarvadavali",
            "Vijay Garden",
            "Dongripada",
            "Tiku-ji-wadi",
            "Manpada (Thane)",
            "Kapurbawdi",
            "Majiwada",
            "Cadbury Junction",
            "Mahapalika Marg",
            "RTO Thane",
            "Teen Haath Naka (Thane)",
            "Mulund Naka",
            "Mulund Fire Station",
            "Sonapur",
            "Shangrila",
            "Bhandup",
            "Bhandup Mahapalika",
            "Naval Housing",
            "Gandhi Nagar (Kanjurmarg)",
            "Surya Nagar",
            "Vikhroli",
            "Godrej Company",
            "Shreyas Cinema",
            "Laxmi Nagar (Ghatkopar)",
            "Pant Nagar",
            "Garodia Nagar",
            "Amar Mahal Junction",
            "Siddharth Colony",
            "Suman Nagar",
            "Anik Nagar Bus Depot",
            "Wadala Truck Terminal",
            "Bhakti Park (Wadala)"
        ]
    },
    red79: {
        code: "M7M9",
        label: "Red Line (Line 7 / 9)",
        route: "Subhash Chandra Bose Stadium to Chhatrapati Shivaji Maharaj International Airport - T2",
        stations: [
            "Subhash Chandra Bose Stadium",
            "Shanti Nagar",
            "Deepak Hospital (Mediya Nagar)",
            "Sai Baba Nagar",
            "Kashigaon",
            "Miragaon",
            "Pandurang Wadi",
            "Dahisar (East)",
            "Ovaripada",
            "Rashtriya Udyan",
            "Devipada",
            "Magathane",
            "Poisar",
            "Akurli",
            "Kurar",
            "Dindoshi",
            "Aarey",
            "Goregaon (East)",
            "Jogeshwari (East)",
            "Mogra",
            "Gundavali",
            "Airport Colony",
            "Chhatrapati Shivaji Maharaj International Airport - T2"
        ]
    },
    yellow2: {
        code: "M2",
        label: "Yellow Line (Line 2A / 2B)",
        route: "Dahisar (East) to Mandale",
        stations: [
            "Dahisar (East)",
            "Anand Nagar",
            "Kandarpada",
            "Mandapeshwar",
            "Eksar",
            "Borivali (West)",
            "Shimpoli",
            "Kandivli (West)",
            "Dahanukarwadi",
            "Valnai-Meeth Chowky",
            "Malad (West)",
            "Lower Malad",
            "Bangur Nagar",
            "Goregaon (West)",
            "Oshiwara",
            "Lower Oshiwara",
            "Andheri (West)",
            "ESIC Nagar",
            "Prem Nagar",
            "Indira Nagar (Vile Parle)",
            "Nanavati Hospital",
            "Khira Nagar",
            "Saraswat Nagar",
            "National College (Bandra)",
            "Bandra",
            "Income Tax Office",
            "ILFS",
            "MTNL",
            "SG Barve Marg",
            "Kurla (East)",
            "Eastern Express Highway",
            "Chembur",
            "Diamond Garden",
            "Shivaji Chowk (Chembur)",
            "Deonar",
            "Mankhurd",
            "Mandale"
        ]
    }
};
