window.MUMBAI_WESTERN_TRAINS = [
    {
        trainNo: "94008",
        trainName: "Virar-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 12,
        acLocal: "Yes",
        dayType: "Weekday",
        stops: [
            { station: "Virar", order: 1, time: "05:57", platform: "3" },
            { station: "Nalasopara", order: 2, time: "06:03", platform: "2" },
            { station: "Vasai", order: 3, time: "06:08", platform: "3" },
            { station: "Naigaon", order: 4, time: "06:13", platform: "2" },
            { station: "Bhayandar", order: 5, time: "06:19", platform: "4" },
            { station: "Mira Road", order: 6, time: "06:24", platform: "2" },
            { station: "Dahisar", order: 7, time: "06:29", platform: "2" },
            { station: "Borivali", order: 8, time: "06:36", platform: "7" },
            { station: "Andheri", order: 9, time: "06:50", platform: "7" },
            { station: "Bandra", order: 10, time: "06:59", platform: "5" },
            { station: "Dadar", order: 11, time: "07:04", platform: "4" },
            { station: "Mumbai Central", order: 12, time: "07:11", platform: "4" },
            { station: "Grant Road", order: 13, time: "07:13", platform: "4" },
            { station: "Charni Road", order: 14, time: "07:15", platform: "4" },
            { station: "Marine Lines", order: 15, time: "07:18", platform: "4" },
            { station: "Churchgate", order: 16, time: "07:22", platform: "2" }
        ]
    },
    {
        trainNo: "92018",
        trainName: "Virar-Andheri",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 15,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Virar", order: 1, time: "06:05", platform: "6" },
            { station: "Nalasopara", order: 2, time: "06:12", platform: "4" },
            { station: "Vasai", order: 3, time: "06:17", platform: "5" },
            { station: "Bhayandar", order: 4, time: "06:25", platform: "6" },
            { station: "Borivali", order: 5, time: "06:35", platform: "8" },
            { station: "Andheri", order: 6, time: "06:52", platform: "9" }
        ]
    },
    {
        trainNo: "90122",
        trainName: "Virar-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Virar", order: 1, time: "06:11", platform: "1" },
            { station: "Nalasopara", order: 2, time: "06:17", platform: "2" },
            { station: "Vasai", order: 3, time: "06:22", platform: "4" },
            { station: "Naigaon", order: 4, time: "06:26", platform: "2" },
            { station: "Bhayandar", order: 5, time: "06:32", platform: "4" },
            { station: "Mira Road", order: 6, time: "06:37", platform: "2" },
            { station: "Dahisar", order: 7, time: "06:41", platform: "2" },
            { station: "Borivali", order: 8, time: "06:46", platform: "7" },
            { station: "Andheri", order: 9, time: "07:02", platform: "7" },
            { station: "Bandra", order: 10, time: "07:12", platform: "5" },
            { station: "Dadar", order: 11, time: "07:18", platform: "4" },
            { station: "Mumbai Central", order: 12, time: "07:25", platform: "4" },
            { station: "Grant Road", order: 13, time: "07:27", platform: "4" },
            { station: "Charni Road", order: 14, time: "07:29", platform: "4" },
            { station: "Marine Lines", order: 15, time: "07:32", platform: "4" },
            { station: "Churchgate", order: 16, time: "07:36", platform: "1" }
        ]
    },
    {
        trainNo: "92020",
        trainName: "Virar-Borivali",
        line: "Western",
        direction: "Down",
        trainType: "Slow",
        carCount: 15,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Virar", order: 1, time: "06:21", platform: "2" },
            { station: "Nalasopara", order: 2, time: "06:27", platform: "2" },
            { station: "Vasai Road", order: 3, time: "06:32", platform: "3" },
            { station: "Naigaon", order: 4, time: "06:36", platform: "2" },
            { station: "Bhayandar", order: 5, time: "06:42", platform: "4" },
            { station: "Mira Road", order: 6, time: "06:47", platform: "2" },
            { station: "Dahisar", order: 7, time: "06:51", platform: "2" },
            { station: "Borivali", order: 8, time: "06:57", platform: "3" }
        ]
    },
    {
        trainNo: "92024",
        trainName: "Virar-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 15,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Virar", order: 1, time: "06:30", platform: "1" },
            { station: "Nalasopara", order: 2, time: "06:36", platform: "2" },
            { station: "Vasai Road", order: 3, time: "06:41", platform: "3" },
            { station: "Naigaon", order: 4, time: "06:46", platform: "2" },
            { station: "Bhayandar", order: 5, time: "06:52", platform: "4" },
            { station: "Mira Road", order: 6, time: "06:58", platform: "2" },
            { station: "Dahisar", order: 7, time: "07:02", platform: "2" },
            { station: "Borivali", order: 8, time: "07:07", platform: "7" },
            { station: "Andheri", order: 9, time: "07:20", platform: "7" },
            { station: "Bandra", order: 10, time: "07:30", platform: "5" },
            { station: "Dadar", order: 11, time: "07:37", platform: "4" },
            { station: "Mumbai Central", order: 12, time: "07:44", platform: "4" },
            { station: "Churchgate", order: 13, time: "07:54", platform: "4" }
        ]
    },
    {
        trainNo: "90152",
        trainName: "Virar-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Slow",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Virar", order: 1, time: "06:44", platform: "1" },
            { station: "Nalasopara", order: 2, time: "06:50", platform: "2" },
            { station: "Vasai", order: 3, time: "06:55", platform: "3" },
            { station: "Naigaon", order: 4, time: "07:00", platform: "2" },
            { station: "Bhayandar", order: 5, time: "07:06", platform: "4" },
            { station: "Mira Road", order: 6, time: "07:11", platform: "2" },
            { station: "Dahisar", order: 7, time: "07:15", platform: "2" },
            { station: "Borivali", order: 8, time: "07:19", platform: "5" },
            { station: "Kandivali", order: 9, time: "07:23", platform: "2" },
            { station: "Malad", order: 10, time: "07:26", platform: "2" },
            { station: "Goregaon", order: 11, time: "07:29", platform: "4" },
            { station: "Ram Mandir", order: 12, time: "07:31", platform: "4" },
            { station: "Jogeshwari", order: 13, time: "07:34", platform: "2" },
            { station: "Andheri", order: 14, time: "07:39", platform: "5" },
            { station: "Vile Parle", order: 15, time: "07:42", platform: "4" },
            { station: "Santa Cruz", order: 16, time: "07:45", platform: "4" },
            { station: "Khar Road", order: 17, time: "07:48", platform: "4" },
            { station: "Bandra", order: 18, time: "07:52", platform: "3" },
            { station: "Mahim Jn", order: 19, time: "07:55", platform: "2" },
            { station: "Matunga Road", order: 20, time: "07:58", platform: "2" },
            { station: "Dadar", order: 21, time: "08:02", platform: "2" },
            { station: "Prabhadevi", order: 22, time: "08:04", platform: "2" },
            { station: "Lower Parel", order: 23, time: "08:07", platform: "2" },
            { station: "Mahalaxmi", order: 24, time: "08:10", platform: "3" },
            { station: "Mumbai Central", order: 25, time: "08:13", platform: "2" },
            { station: "Grant Road", order: 26, time: "08:15", platform: "2" },
            { station: "Charni Road", order: 27, time: "08:17", platform: "2" },
            { station: "Marine Lines", order: 28, time: "08:20", platform: "2" },
            { station: "Churchgate", order: 29, time: "08:24", platform: "2" }
        ]
    },
    {
        trainNo: "90102",
        trainName: "Vasai-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "05:56", platform: "1" },
            { station: "Naigaon", order: 2, time: "06:02", platform: "2" },
            { station: "Bhayandar", order: 3, time: "06:07", platform: "4" },
            { station: "Mira Road", order: 4, time: "06:12", platform: "2" },
            { station: "Dahisar", order: 5, time: "06:16", platform: "2" },
            { station: "Borivali", order: 6, time: "06:22", platform: "7" },
            { station: "Andheri", order: 7, time: "06:34", platform: "7" },
            { station: "Bandra", order: 8, time: "06:43", platform: "5" },
            { station: "Dadar", order: 9, time: "06:49", platform: "4" },
            { station: "Mumbai Central", order: 10, time: "06:56", platform: "4" },
            { station: "Grant Road", order: 11, time: "06:58", platform: "4" },
            { station: "Charni Road", order: 12, time: "07:00", platform: "4" },
            { station: "Marine Lines", order: 13, time: "07:03", platform: "4" },
            { station: "Churchgate", order: 14, time: "07:08", platform: "4" }
        ]
    },
    {
        trainNo: "90146",
        trainName: "Vasai-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "06:43", platform: "1" },
            { station: "Naigaon", order: 2, time: "06:49", platform: "2" },
            { station: "Bhayandar", order: 3, time: "06:55", platform: "4" },
            { station: "Mira Road", order: 4, time: "07:01", platform: "2" },
            { station: "Dahisar", order: 5, time: "07:05", platform: "2" },
            { station: "Borivali", order: 6, time: "07:10", platform: "7" },
            { station: "Andheri", order: 7, time: "07:23", platform: "7" },
            { station: "Bandra", order: 8, time: "07:33", platform: "5" },
            { station: "Dadar", order: 9, time: "07:40", platform: "4" },
            { station: "Mumbai Central", order: 10, time: "07:47", platform: "4" },
            { station: "Grant Road", order: 11, time: "07:49", platform: "4" },
            { station: "Charni Road", order: 12, time: "07:51", platform: "4" },
            { station: "Marine Lines", order: 13, time: "07:54", platform: "4" },
            { station: "Churchgate", order: 14, time: "07:57", platform: "4" }
        ]
    },
    {
        trainNo: "90174",
        trainName: "Vasai-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "07:14", platform: "1" },
            { station: "Naigaon", order: 2, time: "07:20", platform: "2" },
            { station: "Bhayandar", order: 3, time: "07:26", platform: "4" },
            { station: "Mira Road", order: 4, time: "07:31", platform: "2" },
            { station: "Dahisar", order: 5, time: "07:35", platform: "2" },
            { station: "Borivali", order: 6, time: "07:40", platform: "7" },
            { station: "Andheri", order: 7, time: "07:54", platform: "7" },
            { station: "Bandra", order: 8, time: "08:03", platform: "5" },
            { station: "Dadar", order: 9, time: "08:09", platform: "4" },
            { station: "Mumbai Central", order: 10, time: "08:16", platform: "4" },
            { station: "Grant Road", order: 11, time: "08:18", platform: "4" },
            { station: "Charni Road", order: 12, time: "08:21", platform: "4" },
            { station: "Marine Lines", order: 13, time: "08:24", platform: "4" },
            { station: "Churchgate", order: 14, time: "08:29", platform: "4" }
        ]
    },
    {
        trainNo: "92034",
        trainName: "Vasai-Andheri",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 15,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "07:40", platform: "1" },
            { station: "Naigaon", order: 2, time: "07:46", platform: "2" },
            { station: "Bhayandar", order: 3, time: "07:51", platform: "4" },
            { station: "Mira Road", order: 4, time: "07:56", platform: "2" },
            { station: "Dahisar", order: 5, time: "08:01", platform: "2" },
            { station: "Borivali", order: 6, time: "08:05", platform: "8" },
            { station: "Andheri", order: 7, time: "08:23", platform: "8" }
        ]
    },
    {
        trainNo: "90242",
        trainName: "Vasai-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "08:14", platform: "1" },
            { station: "Naigaon", order: 2, time: "08:21", platform: "2" },
            { station: "Bhayandar", order: 3, time: "08:27", platform: "4" },
            { station: "Mira Road", order: 4, time: "08:33", platform: "2" },
            { station: "Dahisar", order: 5, time: "08:37", platform: "2" },
            { station: "Borivali", order: 6, time: "08:43", platform: "7" },
            { station: "Andheri", order: 7, time: "08:59", platform: "7" },
            { station: "Bandra", order: 8, time: "09:08", platform: "5" },
            { station: "Dadar", order: 9, time: "09:14", platform: "4" },
            { station: "Mumbai Central", order: 10, time: "09:21", platform: "4" },
            { station: "Grant Road", order: 11, time: "09:23", platform: "4" },
            { station: "Charni Road", order: 12, time: "09:25", platform: "4" },
            { station: "Marine Lines", order: 13, time: "09:28", platform: "4" },
            { station: "Churchgate", order: 14, time: "09:33", platform: "4" }
        ]
    },
    {
        trainNo: "90266",
        trainName: "Vasai-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "08:47", platform: "1" },
            { station: "Naigaon", order: 2, time: "08:53", platform: "2" },
            { station: "Bhayandar", order: 3, time: "08:59", platform: "4" },
            { station: "Mira Road", order: 4, time: "09:04", platform: "2" },
            { station: "Dahisar", order: 5, time: "09:08", platform: "2" },
            { station: "Borivali", order: 6, time: "09:13", platform: "7" },
            { station: "Andheri", order: 7, time: "09:29", platform: "7" },
            { station: "Bandra", order: 8, time: "09:40", platform: "5" },
            { station: "Dadar", order: 9, time: "09:45", platform: "4" },
            { station: "Mumbai Central", order: 10, time: "09:52", platform: "4" },
            { station: "Grant Road", order: 11, time: "09:54", platform: "4" },
            { station: "Charni Road", order: 12, time: "09:56", platform: "4" },
            { station: "Marine Lines", order: 13, time: "09:59", platform: "4" },
            { station: "Churchgate", order: 14, time: "10:03", platform: "4" }
        ]
    },
    {
        trainNo: "92054",
        trainName: "Vasai-Andheri",
        line: "Western",
        direction: "Down",
        trainType: "Slow",
        carCount: 15,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "09:08", platform: "1" },
            { station: "Naigaon", order: 2, time: "09:14", platform: "2" },
            { station: "Bhayandar", order: 3, time: "09:20", platform: "4" },
            { station: "Mira Road", order: 4, time: "09:25", platform: "2" },
            { station: "Dahisar", order: 5, time: "09:29", platform: "2" },
            { station: "Borivali", order: 6, time: "09:33", platform: "5" },
            { station: "Kandivali", order: 7, time: "09:38", platform: "2" },
            { station: "Malad", order: 8, time: "09:42", platform: "2" },
            { station: "Goregaon", order: 9, time: "09:45", platform: "4" },
            { station: "Ram Mandir", order: 10, time: "09:47", platform: "4" },
            { station: "Jogeshwari", order: 11, time: "09:50", platform: "2" },
            { station: "Andheri", order: 12, time: "09:56", platform: "4" }
        ]
    },
    {
        trainNo: "90350",
        trainName: "Vasai-Churchgate",
        line: "Western",
        direction: "Down",
        trainType: "Slow",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "10:02", platform: "1" },
            { station: "Naigaon", order: 2, time: "10:08", platform: "2" },
            { station: "Bhayandar", order: 3, time: "10:14", platform: "4" },
            { station: "Mira Road", order: 4, time: "10:20", platform: "2" },
            { station: "Dahisar", order: 5, time: "10:24", platform: "2" },
            { station: "Borivali", order: 6, time: "10:28", platform: "5" },
            { station: "Kandivali", order: 7, time: "10:32", platform: "2" },
            { station: "Malad", order: 8, time: "10:35", platform: "2" },
            { station: "Goregaon", order: 9, time: "10:38", platform: "4" },
            { station: "Ram Mandir", order: 10, time: "10:40", platform: "4" },
            { station: "Jogeshwari", order: 11, time: "10:43", platform: "2" },
            { station: "Andheri", order: 12, time: "10:48", platform: "5" },
            { station: "Vile Parle", order: 13, time: "10:53", platform: "4" },
            { station: "Santa Cruz", order: 14, time: "10:56", platform: "4" },
            { station: "Khar Road", order: 15, time: "10:59", platform: "4" },
            { station: "Bandra", order: 16, time: "11:03", platform: "3" },
            { station: "Mahim Jn", order: 17, time: "11:06", platform: "2" },
            { station: "Matunga Road", order: 18, time: "11:09", platform: "2" },
            { station: "Dadar", order: 19, time: "11:13", platform: "2" },
            { station: "Prabhadevi", order: 20, time: "11:15", platform: "2" },
            { station: "Lower Parel", order: 21, time: "11:18", platform: "2" },
            { station: "Mahalaxmi", order: 22, time: "11:21", platform: "3" },
            { station: "Mumbai Central", order: 23, time: "11:24", platform: "2" },
            { station: "Grant Road", order: 24, time: "11:26", platform: "2" },
            { station: "Charni Road", order: 25, time: "11:28", platform: "2" },
            { station: "Marine Lines", order: 26, time: "11:31", platform: "2" },
            { station: "Churchgate", order: 27, time: "11:36", platform: "2" }
        ]
    },
    {
        trainNo: "92082",
        trainName: "Vasai-Andheri",
        line: "Western",
        direction: "Down",
        trainType: "Slow",
        carCount: 15,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "10:58", platform: "1" },
            { station: "Naigaon", order: 2, time: "11:04", platform: "2" },
            { station: "Bhayandar", order: 3, time: "11:10", platform: "4" },
            { station: "Mira Road", order: 4, time: "11:15", platform: "2" },
            { station: "Dahisar", order: 5, time: "11:20", platform: "2" },
            { station: "Borivali", order: 6, time: "11:26", platform: "5" },
            { station: "Kandivali", order: 7, time: "11:32", platform: "2" },
            { station: "Malad", order: 8, time: "11:35", platform: "2" },
            { station: "Goregaon", order: 9, time: "11:38", platform: "4" },
            { station: "Ram Mandir", order: 10, time: "11:40", platform: "4" },
            { station: "Jogeshwari", order: 11, time: "11:43", platform: "2" },
            { station: "Andheri", order: 12, time: "11:49", platform: "4" }
        ]
    },
    {
        trainNo: "92100",
        trainName: "Vasai-Dadar",
        line: "Western",
        direction: "Down",
        trainType: "Fast",
        carCount: 15,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Vasai", order: 1, time: "12:20", platform: "1" },
            { station: "Naigaon", order: 2, time: "12:25", platform: "4" },
            { station: "Bhayandar", order: 3, time: "12:31", platform: "6" },
            { station: "Mira Road", order: 4, time: "12:36", platform: "4" },
            { station: "Dahisar", order: 5, time: "12:40", platform: "4" },
            { station: "Borivali", order: 6, time: "12:44", platform: "7" },
            { station: "Andheri", order: 7, time: "12:57", platform: "7" },
            { station: "Bandra", order: 8, time: "13:06", platform: "5" },
            { station: "Dadar", order: 9, time: "13:16", platform: "5" }
        ]
    },
    {
        trainNo: "90189",
        trainName: "Churchgate-Virar",
        line: "Western",
        direction: "Up",
        trainType: "Fast",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Churchgate", order: 1, time: "07:20", platform: "2" },
            { station: "Marine Lines", order: 2, time: "07:23", platform: "3" },
            { station: "Charni Road", order: 3, time: "07:25", platform: "3" },
            { station: "Grant Road", order: 4, time: "07:27", platform: "4" },
            { station: "Mumbai Central", order: 5, time: "07:30", platform: "4" },
            { station: "Dadar", order: 6, time: "07:36", platform: "5" },
            { station: "Bandra", order: 7, time: "07:42", platform: "4" },
            { station: "Andheri", order: 8, time: "07:50", platform: "6" },
            { station: "Borivali", order: 9, time: "08:05", platform: "7" },
            { station: "Dahisar", order: 10, time: "08:10", platform: "3" },
            { station: "Mira Road", order: 11, time: "08:14", platform: "4" },
            { station: "Bhayandar", order: 12, time: "08:19", platform: "4" },
            { station: "Naigaon", order: 13, time: "08:23", platform: "2" },
            { station: "Vasai", order: 14, time: "08:28", platform: "3" },
            { station: "Nalasopara", order: 15, time: "08:33", platform: "2" },
            { station: "Virar", order: 16, time: "08:38", platform: "4" }
        ]
    },
    {
        trainNo: "91005",
        trainName: "Churchgate-Virar",
        line: "Western",
        direction: "Up",
        trainType: "Fast",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Churchgate", order: 1, time: "11:05", platform: "3" },
            { station: "Marine Lines", order: 2, time: "11:08", platform: "3" },
            { station: "Charni Road", order: 3, time: "11:10", platform: "3" },
            { station: "Grant Road", order: 4, time: "11:13", platform: "3" },
            { station: "Mumbai Central", order: 5, time: "11:15", platform: "3" },
            { station: "Dadar", order: 6, time: "11:23", platform: "3" },
            { station: "Bandra", order: 7, time: "11:28", platform: "4" },
            { station: "Andheri", order: 8, time: "11:37", platform: "6" },
            { station: "Borivali", order: 9, time: "11:52", platform: "6" },
            { station: "Dahisar", order: 10, time: "11:56", platform: "1" },
            { station: "Mira Road", order: 11, time: "12:01", platform: "1" },
            { station: "Bhayandar", order: 12, time: "12:06", platform: "1" },
            { station: "Naigaon", order: 13, time: "12:12", platform: "1" },
            { station: "Vasai", order: 14, time: "12:17", platform: "2" },
            { station: "Nalasopara", order: 15, time: "12:22", platform: "1" },
            { station: "Virar", order: 16, time: "12:29", platform: "3" }
        ]
    },
    {
        trainNo: "94067",
        trainName: "Churchgate-Virar",
        line: "Western",
        direction: "Up",
        trainType: "Fast",
        carCount: 12,
        acLocal: "Yes",
        dayType: "Weekday",
        stops: [
            { station: "Churchgate", order: 1, time: "04:39", platform: "3" },
            { station: "Marine Lines", order: 2, time: "04:42", platform: "3" },
            { station: "Charni Road", order: 3, time: "04:44", platform: "3" },
            { station: "Grant Road", order: 4, time: "04:47", platform: "3" },
            { station: "Mumbai Central", order: 5, time: "04:49", platform: "3" },
            { station: "Dadar", order: 6, time: "04:56", platform: "3" },
            { station: "Bandra", order: 7, time: "05:01", platform: "4" },
            { station: "Andheri", order: 8, time: "05:10", platform: "6" },
            { station: "Borivali", order: 9, time: "05:24", platform: "6" },
            { station: "Dahisar", order: 10, time: "05:30", platform: "1" },
            { station: "Mira Road", order: 11, time: "05:35", platform: "1" },
            { station: "Bhayandar", order: 12, time: "05:40", platform: "1" },
            { station: "Naigaon", order: 13, time: "05:46", platform: "1" },
            { station: "Vasai", order: 14, time: "05:51", platform: "2" },
            { station: "Nalasopara", order: 15, time: "05:56", platform: "1" },
            { station: "Virar", order: 16, time: "06:04", platform: "3" }
        ]
    },
    {
        trainNo: "94069",
        trainName: "Andheri-Virar",
        line: "Western",
        direction: "Up",
        trainType: "Fast",
        carCount: 12,
        acLocal: "Yes",
        dayType: "Weekday",
        stops: [
            { station: "Andheri", order: 1, time: "05:25", platform: "8" },
            { station: "Borivali", order: 2, time: "05:40", platform: "6" },
            { station: "Dahisar", order: 3, time: "05:44", platform: "1" },
            { station: "Mira Road", order: 4, time: "05:49", platform: "1" },
            { station: "Bhayandar", order: 5, time: "05:54", platform: "1" },
            { station: "Naigaon", order: 6, time: "06:00", platform: "1" },
            { station: "Vasai", order: 7, time: "06:05", platform: "2" },
            { station: "Nalasopara", order: 8, time: "06:10", platform: "1" },
            { station: "Virar", order: 9, time: "06:18", platform: "3" }
        ]
    }
];

window.MUMBAI_CENTRAL_TRAINS = [
    {
        trainNo: "97316",
        trainName: "Thane-CSMT",
        line: "Central",
        direction: "Down",
        trainType: "Slow",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Thane", order: 1, time: "06:28", platform: "3" },
            { station: "Mulund", order: 2, time: "06:32", platform: "2" },
            { station: "Nahur", order: 3, time: "06:35", platform: "2" },
            { station: "Bhandup", order: 4, time: "06:38", platform: "2" },
            { station: "Kanjur Marg", order: 5, time: "06:41", platform: "2" },
            { station: "Vikhroli", order: 6, time: "06:44", platform: "2" },
            { station: "Ghatkopar", order: 7, time: "06:48", platform: "2" },
            { station: "Vidyavihar", order: 8, time: "06:51", platform: "2" },
            { station: "Kurla", order: 9, time: "06:54", platform: "4" },
            { station: "Sion", order: 10, time: "06:58", platform: "2" },
            { station: "Matunga", order: 11, time: "07:01", platform: "2" },
            { station: "Dadar", order: 12, time: "07:05", platform: "9" },
            { station: "Parel", order: 13, time: "07:08", platform: "3" },
            { station: "Currey Road", order: 14, time: "07:11", platform: "2" },
            { station: "Chinchpokli", order: 15, time: "07:13", platform: "2" },
            { station: "Byculla", order: 16, time: "07:15", platform: "2" },
            { station: "Sandhurst Road", order: 17, time: "07:18", platform: "2" },
            { station: "Masjid", order: 18, time: "07:21", platform: "4" },
            { station: "CSMT", order: 19, time: "07:24", platform: "0" }
        ]
    },
    {
        trainNo: "97320",
        trainName: "Thane-CSMT",
        line: "Central",
        direction: "Down",
        trainType: "Slow",
        carCount: 12,
        acLocal: "Yes",
        dayType: "Weekday",
        stops: [
            { station: "Thane", order: 1, time: "07:04", platform: "3" },
            { station: "Mulund", order: 2, time: "07:08", platform: "2" },
            { station: "Nahur", order: 3, time: "07:11", platform: "2" },
            { station: "Bhandup", order: 4, time: "07:14", platform: "2" },
            { station: "Kanjur Marg", order: 5, time: "07:17", platform: "2" },
            { station: "Vikhroli", order: 6, time: "07:20", platform: "2" },
            { station: "Ghatkopar", order: 7, time: "07:24", platform: "2" },
            { station: "Vidyavihar", order: 8, time: "07:27", platform: "2" },
            { station: "Kurla", order: 9, time: "07:30", platform: "4" },
            { station: "Sion", order: 10, time: "07:34", platform: "2" },
            { station: "Matunga", order: 11, time: "07:37", platform: "2" },
            { station: "Dadar", order: 12, time: "07:41", platform: "9" },
            { station: "Parel", order: 13, time: "07:44", platform: "3" },
            { station: "Currey Road", order: 14, time: "07:47", platform: "2" },
            { station: "Chinchpokli", order: 15, time: "07:49", platform: "2" },
            { station: "Byculla", order: 16, time: "07:51", platform: "2" },
            { station: "Sandhurst Road", order: 17, time: "07:54", platform: "2" },
            { station: "Masjid", order: 18, time: "07:57", platform: "4" },
            { station: "CSMT", order: 19, time: "08:00", platform: "0" }
        ]
    }
];

window.MUMBAI_HARBOUR_TRAINS = [
    {
        trainNo: "98748",
        trainName: "Goregaon-CSMT",
        line: "Harbour",
        direction: "Down",
        trainType: "Slow",
        carCount: 12,
        acLocal: "No",
        dayType: "Weekday",
        stops: [
            { station: "Goregaon", order: 1, time: "14:59", platform: "2" },
            { station: "Ram Mandir", order: 2, time: "15:03", platform: "2" },
            { station: "Jogeshwari", order: 3, time: "15:06", platform: "6" },
            { station: "Andheri", order: 4, time: "15:10", platform: "2" },
            { station: "Vile Parle", order: 5, time: "15:14", platform: "2" },
            { station: "Santa Cruz", order: 6, time: "15:17", platform: "2" },
            { station: "Khar Road", order: 7, time: "15:20", platform: "2" },
            { station: "Bandra", order: 8, time: "15:24", platform: "7" },
            { station: "Mahim Jn", order: 9, time: "15:27", platform: "6" },
            { station: "Kings Circle", order: 10, time: "15:30", platform: "2" },
            { station: "Vadala Road", order: 11, time: "15:36", platform: "3" },
            { station: "Sewri", order: 12, time: "15:39", platform: "2" },
            { station: "Cotton Green", order: 13, time: "15:42", platform: "2" },
            { station: "Reay Road", order: 14, time: "15:44", platform: "2" },
            { station: "Dockyard Road", order: 15, time: "15:47", platform: "2" },
            { station: "Sandhurst Road", order: 16, time: "15:49", platform: "4" },
            { station: "Masjid", order: 17, time: "15:51", platform: "2" },
            { station: "CSMT", order: 18, time: "15:54", platform: "0" }
        ]
    }
];
